contextual_bandit:
    num_models: 25

generate_data:
    enabled: True
    model_output: Null
    num_actions: 5
    num_epochs: 15
    num_examples: 2000
    num_features: 300
    output_file: 'taming_the_monster/data/generated_data'
    policy:
        complexity: 3
        mean: 0
        std: .1
