generate_data:
    enabled: True
    model_output: Null
    num_actions: 3
    num_epochs: 21
    num_examples: 10000
    num_features: 300
    output_file: 'data/generated_data'
    policy:
        complexity: 500
        mean: 0
        std: .1
